version: v1.0
steps:
  s1:
    command: echo
    arguments:
      - valueFrom: d0
      - value: Hello
  s2:
    command: echo
    arguments:
      - valueFrom: d1
  s3:
    command: echo
    arguments:
      - valueFrom: d2


locations:
  ld:
    hostname: 127.0.0.1
    port: 8080
  l1:
    hostname: 127.0.0.1
    port: 8081
  l2:
    hostname: 127.0.0.1
    port: 8082
  l3:
    hostname: 127.0.0.1
    port: 8083


dependencies:
  d0: first_data.txt
  d1: my_data.txt
  d2: another_data.txt
